version: "3.9"

services:

  # LARAVEL PRODUCER
  lumen-estore:
    build:
      context: ./docker-config/lumen-php-fpm
      dockerfile: Dockerfile
    image: lumen-microservice
    container_name: estore-microservice
    ports:
      - 8080:8080
    volumes:
      - ./lumen-estore:/src
    depends_on:
      - db
    dns:
      - 8.8.8.8
    networks:
      - rabbitmq-net

  lumen-sales:
    build:
      context: ./docker-config/lumen-php-fpm
      dockerfile: Dockerfile
    image: lumen-microservice
    container_name: sales-microservice
    ports:
      - 8081:8080
    volumes:
      - ./lumen-sales:/src
    depends_on:
      - db
    dns:
      - 8.8.8.8
    networks:
      - rabbitmq-net

  lumen-warehouse:
    build:
      context: ./docker-config/lumen-php-fpm
      dockerfile: Dockerfile
    image: lumen-microservice
    container_name: warehouse-microservice
    ports:
      - 8082:8080
    volumes:
      - ./lumen-warehouse:/src
    depends_on:
      - db
    dns:
      - 8.8.8.8
    networks:
      - rabbitmq-net

  # nginx-producer:
  #   image: nginx:alpine
  #   container_name: nginx-laravel-producer
  #   restart: unless-stopped
  #   ports:
  #     - 80:80
  #   volumes:
  #     - ./producer:/var/www
  #     - ./docker/nginx-producer:/etc/nginx/conf.d/
  #   depends_on:
  #     - db
  #     - rabbitmq
  #     - php-fpm-producer
  #   networks:
  #     - rabbitmq-laravel-net

  # # LARAVEL CONSUMER
  # php-fpm-consumer:
  #   image: php-fpm-laravel
  #   build: 
  #     context: ./docker/php-fpm
  #     dockerfile: Dockerfile
  #   container_name: php-fpm-laravel-consumer
  #   restart: unless-stopped
  #   volumes:
  #     - ./consumer:/var/www
  #   depends_on:
  #     - db
  #     - rabbitmq
  #   dns:
  #     - 8.8.8.8
  #   networks:
  #     - rabbitmq-laravel-net

  # nginx-consumer:
  #   image: nginx:alpine
  #   container_name: nginx-laravel-consumer
  #   restart: unless-stopped
  #   ports:
  #     - 81:80
  #   volumes:
  #     - ./consumer:/var/www
  #     - ./docker/nginx-consumer:/etc/nginx/conf.d/
  #   depends_on:
  #     - db
  #     - rabbitmq
  #     - php-fpm-consumer
  #   networks:
  #     - rabbitmq-laravel-net

  db:
    image: mysql:8.0.30
    container_name: db-mysql
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
    ports:
      - 3306:3306
    networks:
      - rabbitmq-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    restart: unless-stopped
    # volumes:
    #   - ./docker/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
    #   - ./docker/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
    networks:
      - rabbitmq-net

networks:
  rabbitmq-net:
    driver: bridge
